galaxy_info:
  role_name: k8s_setup
  author: Thibault Caremelle
  description: Setup Kubernetes cluster locally with kubeadm, containerd, and Calico.
  company: none
  license: MIT
  min_ansible_version: "2.11"
