galaxy_info:
  role_name: k8s_setup
  author: Thibault Caremelle
  description: Setup Kubernetes cluster locally
  company: none
  license: MIT
  min_ansible_version: "2.11"

# dependencies:
#   - role: docker-setup
