---
- name: Include docker role
  include_role:
    name: docker-setup

- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes

# Setup Containerd
- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes
  become: true

- name: Generate and modify containerd config with SystemdCgroup enabled
  ansible.builtin.shell: |
    containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  become: true

- name: Ensure containerd is enabled and restarted
  systemd:
    name: containerd
    enabled: yes
    state: restarted
  become: true

# Setup Kubernetes components
- name: Add Kubernetes repository GPG key
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kube_minor_version }}/deb/Release.key |
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Add Kubernetes apt repository source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_minor_version }}/deb/ /"
    state: present
    filename: kubernetes
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: true

- name: Mark Kubernetes packages to hold
  ansible.builtin.command: apt-mark hold {{ item }}
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Initialize Kubernetes cluster
  ansible.builtin.shell: |
    kubeadm init \
      --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
      --pod-network-cidr={{ calico_pod_cidr }} \
      --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  become: true

- name: Create .kube directory
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy Kubernetes admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    remote_src: yes
  become: true

# # Setup Calico network plugin
- name: Create Tigera Operator (CRDs and operator deployment)
  ansible.builtin.command:
    cmd: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml
  become: true
  become_user: "{{ ansible_user }}"
  register: tigera_operator
  failed_when: >
    tigera_operator.rc != 0 and 'already exists' not in (tigera_operator.stderr | default(''))

- name: Render Calico custom resources template
  ansible.builtin.template:
    src: calico-custom-resources.yaml.j2
    dest: /tmp/calico-custom-resources.yaml
    mode: '0644'

- name: Create Calico custom resources
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/calico-custom-resources.yaml
  become: true
  become_user: "{{ ansible_user }}"
  register: custom_resources
  failed_when: >
    custom_resources.rc != 0 and 'already exists' not in (custom_resources.stderr | default(''))