---
- name: Setup Kubernetes and Helm
  hosts: master
  roles:
    - k8s-setup
    - helm-install
  tasks:
    - name: Deploy ArgoCD with Helmfile
      ansible.builtin.command:
        cmd: helmfile apply
        chdir: "{{ playbook_dir }}/../helmfile"
      register: helmfile_output

